packages:
  - 'packages/*'
  - 'playground'
minimumReleaseAge: 1440
strictPeerDependencies: true
allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  cbor-extract: true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
