// AUTO-GENERATED by @lupinum/ginko-cms — edit this file to configure auth providers
import { getAuthConfigProvider, type AuthConfig } from '@lupinum/ginko-cms/convex/auth-config'

export default {
  providers: [getAuthConfigProvider()],
} satisfies AuthConfig
