// AUTO-GENERATED by @lupinum/ginko-cms — edit this file to configure auth providers
import { getConvexAuthProvider } from 'better-convex-nuxt/convex-auth'
import type { AuthConfig } from 'convex/server'

export default {
  providers: [getConvexAuthProvider()],
} satisfies AuthConfig
