// AUTO-GENERATED by @lupinum/ginko-cms — do not edit manually
import { defineGinkoAuth } from '@lupinum/ginko-cms/convex/auth'

import { components, internal } from './_generated/api'
import authConfig from './auth.config'

export const { authComponent, createAuth, createUserIfNeeded } = defineGinkoAuth(
  { components, internal, authConfig },
  {
    emailPassword: true,
  },
)
