// AUTO-GENERATED by @lupinum/ginko-cms — do not edit manually
import { defineGinkoAuth } from '@lupinum/ginko-cms/convex/auth'

import { components, internal } from './_generated/api'
import authConfig from './auth.config'
import authSchema from './betterAuth/schema'

export const { authComponent, createAuth, createAuthOptions } = defineGinkoAuth(
  { components, internal, authConfig, authSchema },
  {
    emailPassword: true,
  },
)
