// AUTO-GENERATED by @lupinum/ginko-cms — do not edit manually
import { httpRouter } from 'convex/server'

import { auth } from './auth'
// GINKO_MCP_BEGIN
import { handle as mcp } from './ginkoCms/mcp'
// GINKO_MCP_END

const http = httpRouter()

auth.registerRoutes(http)
// GINKO_MCP_BEGIN
http.route({ path: '/mcp', method: 'GET', handler: mcp })
http.route({ path: '/mcp', method: 'POST', handler: mcp })
http.route({ path: '/mcp', method: 'DELETE', handler: mcp })
http.route({ path: '/.well-known/oauth-protected-resource/mcp', method: 'GET', handler: mcp })
http.route({ path: '/.well-known/oauth-protected-resource/mcp', method: 'OPTIONS', handler: mcp })
// GINKO_MCP_END

export default http
