// AUTO-GENERATED by @lupinum/ginko-cms — do not edit manually
import { httpRouter } from 'convex/server'

import { authComponent, createAuth } from './auth'
// GINKO_MCP_BEGIN
import { handle as mcp } from './ginkoCms/mcp'
// GINKO_MCP_END

const http = httpRouter()

authComponent.registerRoutes(http, createAuth)
// GINKO_MCP_BEGIN
http.route({ path: '/mcp', method: 'GET', handler: mcp })
http.route({ path: '/mcp', method: 'POST', handler: mcp })
http.route({ path: '/mcp', method: 'DELETE', handler: mcp })
// GINKO_MCP_END

export default http
