// @trellis-bridge-package: @lupinum/ginko-cms
// @trellis-bridge-version: 0.1.3
// AUTO-GENERATED by @lupinum/ginko-cms — do not edit manually
import { defineGinkoAuth } from '@lupinum/ginko-cms/convex/auth'

import { components, internal } from './_generated/api'
import { mutation } from './_generated/server'
import authConfig from './auth.config'

export const { authComponent, createAuth, createUserIfNeeded } = defineGinkoAuth(
  { components, internal, mutation, authConfig },
  {
    emailPassword: true
  }
)
