// AUTO-GENERATED by @lupinum/ginko-cms — do not edit manually
import { defineGinkoAuth } from '@lupinum/ginko-cms/convex/auth'

import { components } from './_generated/api'
import { sendGinkoPasswordResetEmail } from './ginkoCms/passwordRecovery'

export const { authComponent, createAuth } = defineGinkoAuth(
  { components },
  {
    emailPassword: true,
    passwordRecovery: {
      sendResetPassword: async ({ user, url }) => await sendGinkoPasswordResetEmail({ user, url }),
      tokenExpiresInSeconds: 60 * 60,
    },
  },
)

export const { rotateSigningKey } = authComponent.jwksOperatorFunctions(createAuth)
