// @trellis-bridge-package: @lupinum/ginko-cms
// @trellis-bridge-version: 0.1.2
// AUTO-GENERATED by Trellis - do not edit manually
import { createMcpBridge } from '@lupinum/ginko-cms/bridge'
import { components } from './_generated/api'
import { internalMutation } from './_generated/server'
import { component } from './ginkoCms/_caller'

const bridge = createMcpBridge({
  component: component,
  components: components.ginkoCms,
  internalMutation: internalMutation
})

export const consumeToken = bridge.consumeToken
export const getAccessContext = bridge.getAccessContext
export const exportBackup = bridge.exportBackup
export const getAsset = bridge.getAsset
export const resolveAssetUrls = bridge.resolveAssetUrls
export const moveAsset = bridge.moveAsset
export const deleteAsset = bridge.deleteAsset
export const previewDeleteAssetOperation = bridge.previewDeleteAssetOperation
export const listCollections = bridge.listCollections
export const getCollection = bridge.getCollection
export const page = bridge.page
export const list = bridge.list
export const search = bridge.search
export const nav = bridge.nav
export const sitemap = bridge.sitemap
export const explainPublicVisibility = bridge.explainPublicVisibility
export const listEntries = bridge.listEntries
export const getEntry = bridge.getEntry
export const previewArchiveEntryOperation = bridge.previewArchiveEntryOperation
export const previewDeleteEntryOperation = bridge.previewDeleteEntryOperation
export const previewUnpublishEntryOperation = bridge.previewUnpublishEntryOperation
export const createEntry = bridge.createEntry
export const saveEntryDraft = bridge.saveEntryDraft
export const publishEntry = bridge.publishEntry
export const previewPublishEntryOperation = bridge.previewPublishEntryOperation
export const unpublishEntry = bridge.unpublishEntry
export const archiveEntry = bridge.archiveEntry
export const unarchiveEntry = bridge.unarchiveEntry
export const deleteEntry = bridge.deleteEntry
