// @trellis-bridge-package: @lupinum/ginko-cms
// @trellis-bridge-version: 0.1.3
// AUTO-GENERATED by @lupinum/ginko-cms — do not edit manually
import { httpRouter } from 'convex/server'

import { authComponent, createAuth } from './auth'

const http = httpRouter()

authComponent.registerRoutes(http, createAuth)

export default http
