// AUTO-GENERATED by @lupinum/ginko-cms — do not edit manually
import { httpRouter } from 'convex/server'

import { authComponent, createAuth } from './auth'
import { handle as mcp } from './ginkoCms/mcp'

const http = httpRouter()

authComponent.registerRoutes(http, createAuth)
http.route({ path: '/mcp', method: 'GET', handler: mcp })
http.route({ path: '/mcp', method: 'POST', handler: mcp })
http.route({ path: '/mcp', method: 'DELETE', handler: mcp })
http.route({ path: '/.well-known/oauth-protected-resource/mcp', method: 'GET', handler: mcp })
http.route({ path: '/.well-known/oauth-protected-resource/mcp', method: 'OPTIONS', handler: mcp })

export default http
