import {
  archiveEntry as archiveEntryArgs,
  createCheckpoint as createCheckpointArgs,
  createEntry as createEntryArgs,
  createLocaleVariant as createLocaleVariantArgs,
  deleteEntry as deleteEntryArgs,
  getDraftVsPublishedDiff as getDraftVsPublishedDiffArgs,
  getEntry as getEntryArgs,
  getEntryActivity as getEntryActivityArgs,
  getStudioOverview as getStudioOverviewArgs,
  getVersionDiff as getVersionDiffArgs,
  getVersionSnapshot as getVersionSnapshotArgs,
  listActivity as listActivityArgs,
  listEntries as listEntriesArgs,
  listEntriesForStudio as listEntriesForStudioArgs,
  listEntrySummaries as listEntrySummariesArgs,
  listVersions as listVersionsArgs,
  publishEntry as publishEntryArgs,
  reorderEntry as reorderEntryArgs,
  reparentEntry as reparentEntryArgs,
  revertDraftToPublished as revertDraftToPublishedArgs,
  rollbackVersion as rollbackVersionArgs,
  saveEntryDraft as saveEntryDraftArgs,
  unarchiveEntry as unarchiveEntryArgs,
  unpublishEntry as unpublishEntryArgs,
} from '@lupinum/ginko-cms-contract/convex/schemas/editor.js'
import {
  activityListResultValidator,
  draftSaveResultValidator,
  draftVsPublishedDiffValidator,
  entryActivityItemValidator,
  entryListItemValidator,
  entrySummaryValidator,
  publishResultValidator,
  rollbackResultValidator,
  studioEntryListResultValidator,
  studioEntryValidator,
  studioOverviewValidator,
  versionDiffValidator,
  versionListItemValidator,
  versionSnapshotPreviewValidator,
} from '@lupinum/ginko-cms-contract/convex/validators.js'
import { cmsOperationPreviewValidator } from './operation-runtime'
import { v } from 'convex/values'

import { createBridgeModule, type BridgeEntry } from './create.js'

function confirmedArgs<TArgs extends Record<string, unknown>>(args: TArgs) {
  return {
    ...args,
    _confirmationToken: v.string(),
  }
}

export const entries = [
  {
    exportName: 'listEntries',
    operation: 'query',
    component: 'listEntries',
    args: listEntriesArgs.args,
    returns: v.array(entryListItemValidator),
  },
  {
    exportName: 'listEntriesForStudio',
    operation: 'query',
    component: 'listEntriesForStudio',
    args: listEntriesForStudioArgs.args,
    returns: studioEntryListResultValidator,
  },
  {
    exportName: 'listEntrySummaries',
    operation: 'query',
    component: 'listEntrySummaries',
    args: listEntrySummariesArgs.args,
    returns: v.array(entrySummaryValidator),
  },
  {
    exportName: 'getStudioOverview',
    operation: 'query',
    component: 'getStudioOverview',
    args: getStudioOverviewArgs.args,
    returns: studioOverviewValidator,
  },
  {
    exportName: 'getEntry',
    operation: 'query',
    component: 'getEntry',
    args: getEntryArgs.args,
    returns: v.union(v.null(), studioEntryValidator),
  },
  {
    exportName: 'listActivity',
    operation: 'query',
    component: 'listActivity',
    args: listActivityArgs.args,
    returns: activityListResultValidator,
  },
  {
    exportName: 'listVersions',
    operation: 'query',
    component: 'listVersions',
    args: listVersionsArgs.args,
    returns: v.array(versionListItemValidator),
  },
  {
    exportName: 'getVersionDiff',
    operation: 'query',
    component: 'getVersionDiff',
    args: getVersionDiffArgs.args,
    returns: versionDiffValidator,
  },
  {
    exportName: 'getVersionSnapshot',
    operation: 'query',
    component: 'getVersionSnapshot',
    args: getVersionSnapshotArgs.args,
    returns: versionSnapshotPreviewValidator,
  },
  {
    exportName: 'getDraftVsPublishedDiff',
    operation: 'query',
    component: 'getDraftVsPublishedDiff',
    args: getDraftVsPublishedDiffArgs.args,
    returns: draftVsPublishedDiffValidator,
  },
  {
    exportName: 'getEntryActivity',
    operation: 'query',
    component: 'getEntryActivity',
    args: getEntryActivityArgs.args,
    returns: v.array(entryActivityItemValidator),
  },
  {
    exportName: 'createEntry',
    operation: 'mutation',
    component: 'createEntry',
    args: createEntryArgs.args,
    returns: v.string(),
  },
  {
    exportName: 'createLocaleVariant',
    operation: 'mutation',
    component: 'createLocaleVariant',
    args: createLocaleVariantArgs.args,
    returns: v.string(),
  },
  {
    exportName: 'saveEntryDraft',
    operation: 'mutation',
    component: 'saveEntryDraft',
    args: saveEntryDraftArgs.args,
    returns: draftSaveResultValidator,
  },
  {
    exportName: 'publishEntry',
    operation: 'mutation',
    component: 'publishEntryOperationExecute',
    args: confirmedArgs(publishEntryArgs.args),
    returns: publishResultValidator,
  },
  {
    exportName: 'previewPublishEntryOperation',
    operation: 'mutation',
    component: 'previewPublishEntryOperation',
    args: publishEntryArgs.args,
    returns: cmsOperationPreviewValidator(),
  },
  {
    exportName: 'unpublishEntry',
    operation: 'mutation',
    component: 'unpublishEntryOperationExecute',
    args: confirmedArgs(unpublishEntryArgs.args),
    returns: v.null(),
  },
  {
    exportName: 'previewUnpublishEntryOperation',
    operation: 'mutation',
    component: 'previewUnpublishEntryOperation',
    args: unpublishEntryArgs.args,
    returns: cmsOperationPreviewValidator(),
  },
  {
    exportName: 'archiveEntry',
    operation: 'mutation',
    component: 'archiveEntryOperationExecute',
    args: confirmedArgs(archiveEntryArgs.args),
    returns: v.null(),
  },
  {
    exportName: 'previewArchiveEntryOperation',
    operation: 'mutation',
    component: 'previewArchiveEntryOperation',
    args: archiveEntryArgs.args,
    returns: cmsOperationPreviewValidator(),
  },
  {
    exportName: 'unarchiveEntry',
    operation: 'mutation',
    component: 'unarchiveEntry',
    args: unarchiveEntryArgs.args,
    returns: v.null(),
  },
  {
    exportName: 'revertDraftToPublished',
    operation: 'mutation',
    component: 'revertDraftToPublishedOperationExecute',
    args: confirmedArgs(revertDraftToPublishedArgs.args),
    returns: draftSaveResultValidator,
  },
  {
    exportName: 'rollbackVersion',
    operation: 'mutation',
    component: 'rollbackVersionOperationExecute',
    args: confirmedArgs(rollbackVersionArgs.args),
    returns: rollbackResultValidator,
  },
  {
    exportName: 'previewRollbackVersionOperation',
    operation: 'mutation',
    component: 'previewRollbackVersionOperation',
    args: rollbackVersionArgs.args,
    returns: cmsOperationPreviewValidator(),
  },
  {
    exportName: 'createCheckpoint',
    operation: 'mutation',
    component: 'createCheckpoint',
    args: createCheckpointArgs.args,
    returns: v.string(),
  },
  {
    exportName: 'reorderEntry',
    operation: 'mutation',
    component: 'reorderEntry',
    args: reorderEntryArgs.args,
    returns: v.null(),
  },
  {
    exportName: 'reparentEntry',
    operation: 'mutation',
    component: 'reparentEntry',
    args: reparentEntryArgs.args,
    returns: v.null(),
  },
  {
    exportName: 'deleteEntry',
    operation: 'mutation',
    component: 'deleteEntryOperationExecute',
    args: confirmedArgs(deleteEntryArgs.args),
    returns: v.null(),
  },
  {
    exportName: 'previewDeleteEntryOperation',
    operation: 'mutation',
    component: 'previewDeleteEntryOperation',
    args: deleteEntryArgs.args,
    returns: cmsOperationPreviewValidator(),
  },
] as const satisfies readonly BridgeEntry[]

export function createEditorBridge(options: {
  component: Parameters<typeof createBridgeModule>[0]
  components: Record<string, unknown>
}) {
  return createBridgeModule(options.component, options.components, entries)
}
