<script setup lang="ts">
import { computed, ref, watch } from 'vue'

import { useCmsI18n } from '../../../composables/useCmsI18n'
import { slugifyStudioText } from '../../../lib/slug'
import type { FieldContext, FieldDefinition } from './useFieldCommon'

const props = defineProps<{
  field: FieldDefinition
  modelValue: unknown
  context?: FieldContext
  label: string
  fieldError: string | null
}>()

const emit = defineEmits<{
  'update:modelValue': [value: unknown]
}>()

const { t } = useCmsI18n()
const value = computed({
  get: () => props.modelValue,
  set: (v) => emit('update:modelValue', v),
})

const slugManuallyEdited = ref(false)

if (props.field.type === 'slug' && props.field.slugFrom) {
  watch(
    () => props.context?.[props.field.slugFrom!],
    (sourceValue) => {
      if (slugManuallyEdited.value || !sourceValue || typeof sourceValue !== 'string') return
      value.value = slugifyStudioText(sourceValue)
    },
  )
}
</script>

<template>
  <StudioFieldShell
    :for="field.key"
    :label="label"
    :required="field.required"
    :description="
      field.type === 'slug' && field.slugFrom
        ? t('ginkoCms.studio.fieldRenderer.slugAutoGenerated', {
            field: field.slugFrom,
            edited: slugManuallyEdited ? t('ginkoCms.studio.fieldRenderer.slugManualEdited') : '',
          })
        : field.description
    "
    :error="fieldError"
  >
    <Input
      :id="field.key"
      v-model="value"
      :data-testid="`cms-field-${field.key}`"
      :type="field.type === 'email' ? 'email' : field.type === 'url' ? 'url' : 'text'"
      :placeholder="t('ginkoCms.studio.fieldRenderer.textPlaceholder', { label })"
      :class="[
        field.type === 'slug' ? 'ginko:font-mono ginko:text-sm' : '',
        fieldError ? 'ginko:border-destructive' : '',
      ]"
      @input="field.type === 'slug' && field.slugFrom ? (slugManuallyEdited = true) : void 0"
    />
  </StudioFieldShell>
</template>
