// @ginko-cms-bridge-package: @lupinum/ginko-cms
// @ginko-cms-bridge-version: 0.1.0
// Generated by Ginko CMS - do not edit manually
import { createBackupBridge } from '@lupinum/ginko-cms/bridge'

import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createBackupBridge({
  component: component,
  components: components.ginkoCms.backup,
})

export const exportBackup = bridge.exportBackup
export const downloadBackup = bridge.downloadBackup
export const verifyBackup = bridge.verifyBackup
export const deleteBackupArtifact = bridge.deleteBackupArtifact
export const previewDeleteBackupArtifactOperation = bridge.previewDeleteBackupArtifactOperation
