// @ginko-cms-bridge-package: @lupinum/ginko-cms
// @ginko-cms-bridge-version: 0.1.0
// Generated by Ginko CMS - do not edit manually
import { createCollectionContractsBridge } from '@lupinum/ginko-cms/bridge'

import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createCollectionContractsBridge({
  component: component,
  components: components.ginkoCms.collections,
})

export const listCollections = bridge.listCollections
export const getCollection = bridge.getCollection
export const checkCollectionContracts = bridge.checkCollectionContracts
export const installCollectionContracts = bridge.installCollectionContracts
