// @ginko-cms-bridge-package: @lupinum/ginko-cms
// @ginko-cms-bridge-version: 0.1.0
// Generated by Ginko CMS - do not edit manually
import { createDiagnosticsBridge } from '@lupinum/ginko-cms/bridge'

import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createDiagnosticsBridge({
  component: component,
  components: components.ginkoCms.diagnostics,
})

export const validatePublicRoutes = bridge.validatePublicRoutes
export const explainPublicVisibility = bridge.explainPublicVisibility
export const previewPublishImpact = bridge.previewPublishImpact
export const storageHygieneReport = bridge.storageHygieneReport
