// @trellis-bridge-package: @lupinum/ginko-cms
// @trellis-bridge-version: 0.1.0
// AUTO-GENERATED by Trellis - do not edit manually
import { createEditorBridge } from '@lupinum/ginko-cms/bridge'

import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createEditorBridge({
  component: component,
  components: components.ginkoCms.editor,
})

export const listEntries = bridge.listEntries
export const listEntriesForStudio = bridge.listEntriesForStudio
export const listEntrySummaries = bridge.listEntrySummaries
export const getStudioOverview = bridge.getStudioOverview
export const getEntry = bridge.getEntry
export const listActivity = bridge.listActivity
export const listVersions = bridge.listVersions
export const getVersionDiff = bridge.getVersionDiff
export const getVersionSnapshot = bridge.getVersionSnapshot
export const getDraftVsPublishedDiff = bridge.getDraftVsPublishedDiff
export const getEntryActivity = bridge.getEntryActivity
export const createEntry = bridge.createEntry
export const createLocaleVariant = bridge.createLocaleVariant
export const saveEntryDraft = bridge.saveEntryDraft
export const publishEntry = bridge.publishEntry
export const previewPublishEntryOperation = bridge.previewPublishEntryOperation
export const unpublishEntry = bridge.unpublishEntry
export const previewUnpublishEntryOperation = bridge.previewUnpublishEntryOperation
export const archiveEntry = bridge.archiveEntry
export const previewArchiveEntryOperation = bridge.previewArchiveEntryOperation
export const unarchiveEntry = bridge.unarchiveEntry
export const revertDraftToPublished = bridge.revertDraftToPublished
export const rollbackVersion = bridge.rollbackVersion
export const previewRollbackVersionOperation = bridge.previewRollbackVersionOperation
export const createCheckpoint = bridge.createCheckpoint
export const reorderEntry = bridge.reorderEntry
export const reparentEntry = bridge.reparentEntry
export const deleteEntry = bridge.deleteEntry
export const previewDeleteEntryOperation = bridge.previewDeleteEntryOperation
