// @ginko-cms-bridge-package: @lupinum/ginko-cms
// @ginko-cms-bridge-version: 0.1.0
// Generated by Ginko CMS - do not edit manually
import { createImportsBridge } from '@lupinum/ginko-cms/bridge'

import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createImportsBridge({
  component: component,
  components: components.ginkoCms.imports,
})

export const previewImport = bridge.previewImport
export const applyImport = bridge.applyImport
export const listImportRuns = bridge.listImportRuns
