// @ginko-cms-bridge-package: @lupinum/ginko-cms
// @ginko-cms-bridge-version: 0.1.0
// Generated by Ginko CMS - do not edit manually
import { createMcpKeysBridge } from '@lupinum/ginko-cms/bridge'

import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createMcpKeysBridge({
  component: component,
  components: components.ginkoCms.mcpKeys,
})

export const list = bridge.list
export const create = bridge.create
export const revoke = bridge.revoke
