// @trellis-bridge-package: @lupinum/ginko-cms
// @trellis-bridge-version: 0.1.0
// AUTO-GENERATED by Trellis - do not edit manually
import { createMembersBridge } from '@lupinum/ginko-cms/bridge'

import { components } from '../_generated/api'
import { mutation } from '../_generated/server'
import { component } from './_caller'

const bridge = createMembersBridge({
  component: component,
  components: components.ginkoCms.members,
  mutation: mutation,
})

export const getAccessContext = bridge.getAccessContext
export const listMembers = bridge.listMembers
export const getMember = bridge.getMember
export const addMember = bridge.addMember
export const updateMemberRole = bridge.updateMemberRole
export const removeMember = bridge.removeMember
export const bootstrapCmsOwner = bridge.bootstrapCmsOwner
