// AUTO-GENERATED by @lupinum/ginko-cms — do not edit manually

declare const process: {
  env: Record<string, string | undefined>
}

function requiredEnvironmentValue(name: string): string {
  const value = process.env[name]?.trim()
  if (!value) throw new Error(`Password recovery is not configured: ${name} is required.`)
  return value
}

function passwordRecoveryEndpoint(): string {
  const value = requiredEnvironmentValue('GINKO_CMS_PASSWORD_RESET_WEBHOOK_URL')
  const url = new URL(value)
  if (url.protocol !== 'https:' || url.username || url.password) {
    throw new Error(
      'Password recovery is not configured: the webhook must be an HTTPS URL without embedded credentials.',
    )
  }
  return url.toString()
}

/**
 * Delivers a provider-owned Better Auth recovery URL to the host's approved
 * email webhook. The reset token remains inside the one-time URL and is never
 * logged or persisted by Ginko CMS.
 */
export async function sendGinkoPasswordResetEmail(input: {
  user: { email: string; name: string }
  url: string
}): Promise<void> {
  const response = await fetch(passwordRecoveryEndpoint(), {
    method: 'POST',
    redirect: 'error',
    signal: AbortSignal.timeout(10_000),
    headers: {
      authorization: `Bearer ${requiredEnvironmentValue('GINKO_CMS_PASSWORD_RESET_WEBHOOK_TOKEN')}`,
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      event: 'ginko-cms.password-recovery.requested',
      recipient: { email: input.user.email, name: input.user.name },
      recoveryUrl: input.url,
    }),
  })
  if (!response.ok) {
    throw new Error(`Password recovery delivery failed with status ${response.status}.`)
  }
}
