// @ginko-cms-bridge-package: @lupinum/ginko-cms
// @ginko-cms-bridge-version: 0.1.0
// Generated by Ginko CMS - do not edit manually
import { createPublicBridge } from '@lupinum/ginko-cms/bridge'

import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createPublicBridge({
  component: component,
  components: components.ginkoCms.public,
})

export const page = bridge.page
export const routeMeta = bridge.routeMeta
export const list = bridge.list
export const nav = bridge.nav
export const surround = bridge.surround
export const search = bridge.search
export const sitemap = bridge.sitemap
export const singleton = bridge.singleton
export const siteData = bridge.siteData
