// @ginko-cms-bridge-package: @lupinum/ginko-cms
// @ginko-cms-bridge-version: 0.1.0
// Generated by Ginko CMS - do not edit manually
import { createSettingsBridge } from '@lupinum/ginko-cms/bridge'

import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createSettingsBridge({
  component: component,
  components: components.ginkoCms.settings,
})

export const getStudioSettings = bridge.getStudioSettings
export const getSettings = bridge.getSettings
export const updateSettings = bridge.updateSettings
