// AUTO-GENERATED by @lupinum/ginko-cms — used by Better Auth schema generation
import { createAuth } from '../auth'

// Better Auth's schema generator only inspects the static auth model and does
// not execute Convex context methods. Keep its required placeholder isolated
// to this tooling-only boundary instead of weakening application types.
const schemaGenerationContext = {} as Parameters<typeof createAuth>[0]

export const auth = createAuth(schemaGenerationContext)
