import { defineArgs } from '@lupinum/trellis/args'

import { internal } from '#trellis/api'

// AUTO-GENERATED by @lupinum/ginko-cms — do not edit manually
import { projectTool, type ProjectToolDefinition } from '../../_shared/project-tool-runtime'

const schema = defineArgs({
  description: 'List all CMS collections.',
  args: {},
})

const tool: ProjectToolDefinition = projectTool({
  schema: schema,
  call: internal.ginkoCmsMcp.listCollections,
  capability: 'readCms',
  meta: {
    name: 'list-collections',
  },
  group: 'collections',
  respond: ({ args, result, ok, error }) => {
    void args
    void error
    const collections = result
    return ok(
      { collections: collections },
      `Found ${collections.length} collection${collections.length === 1 ? '' : 's'}.`,
    )
  },
  operation: 'query',
})

export default tool
