// @trellis-bridge-package: @lupinum/ginko-cms
// @trellis-bridge-version: 0.1.2
// AUTO-GENERATED by Trellis - do not edit manually
import { createAssetsBridge } from '@lupinum/ginko-cms/bridge'
import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createAssetsBridge({
  component: component,
  components: components.ginkoCms.assets
})

export const generateUploadUrl = bridge.generateUploadUrl
export const registerAsset = bridge.registerAsset
export const attachAssetsToEntry = bridge.attachAssetsToEntry
export const updateAsset = bridge.updateAsset
export const moveAsset = bridge.moveAsset
export const getAssetUrl = bridge.getAssetUrl
export const getAsset = bridge.getAsset
export const listColocatedAssets = bridge.listColocatedAssets
export const resolveAssetUrls = bridge.resolveAssetUrls
export const getAssetManagerData = bridge.getAssetManagerData
export const deleteAsset = bridge.deleteAsset
export const previewDeleteAssetOperation = bridge.previewDeleteAssetOperation
export const restoreAsset = bridge.restoreAsset
export const purgeAsset = bridge.purgeAsset
