// @trellis-bridge-package: @lupinum/ginko-cms
// @trellis-bridge-version: 0.1.2
// AUTO-GENERATED by Trellis - do not edit manually
import { createDiagnosticsBridge } from '@lupinum/ginko-cms/bridge'
import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createDiagnosticsBridge({
  component: component,
  components: components.ginkoCms.diagnostics
})

export const validatePublicRoutes = bridge.validatePublicRoutes
export const explainPublicVisibility = bridge.explainPublicVisibility
export const previewPublishImpact = bridge.previewPublishImpact
export const storageHygieneReport = bridge.storageHygieneReport
