// @trellis-bridge-package: @lupinum/ginko-cms
// @trellis-bridge-version: 0.1.1
// AUTO-GENERATED by Trellis - do not edit manually
import { createImportsBridge } from '@lupinum/ginko-cms/bridge'
import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createImportsBridge({
  component: component,
  components: components.ginkoCms.imports
})

export const previewImport = bridge.previewImport
export const applyImport = bridge.applyImport
export const listImportRuns = bridge.listImportRuns
