// @trellis-bridge-package: @lupinum/ginko-cms
// @trellis-bridge-version: 0.1.3
// AUTO-GENERATED by Trellis - do not edit manually
import { createMcpKeysBridge } from '@lupinum/ginko-cms/bridge'
import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createMcpKeysBridge({
  component: component,
  components: components.ginkoCms.mcpKeys
})

export const list = bridge.list
export const create = bridge.create
export const revoke = bridge.revoke
