// @ginko-cms-bridge-package: @lupinum/ginko-cms
// @ginko-cms-bridge-version: 0.1.3
// Generated by Ginko CMS - do not edit manually
import { createMembersBridge } from '@lupinum/ginko-cms/bridge'
import { components } from '../_generated/api'
import { mutation } from '../_generated/server'
import { component } from './_caller'

const bridge = createMembersBridge({
  component: component,
  components: components.ginkoCms.members,
  mutation: mutation
})

export const getAccessContext = bridge.getAccessContext
export const listMembers = bridge.listMembers
export const getMember = bridge.getMember
export const addMember = bridge.addMember
export const updateMemberRole = bridge.updateMemberRole
export const removeMember = bridge.removeMember
export const previewRemoveMemberOperation = bridge.previewRemoveMemberOperation
export const bootstrapCmsOwner = bridge.bootstrapCmsOwner
