// @ginko-cms-bridge-package: @lupinum/ginko-cms
// @ginko-cms-bridge-version: 0.1.3
// Generated by Ginko CMS - do not edit manually
import { createMigrationsBridge } from '@lupinum/ginko-cms/bridge'
import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createMigrationsBridge({
  component: component,
  components: components.ginkoCms.migrations
})

export const listContentMigrationEntries = bridge.listContentMigrationEntries
export const applyContentMigrationEntries = bridge.applyContentMigrationEntries
