// @trellis-bridge-package: @lupinum/ginko-cms
// @trellis-bridge-version: 0.1.0
// AUTO-GENERATED by Trellis - do not edit manually
import { createMigrationsBridge } from '@lupinum/ginko-cms/bridge'
import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createMigrationsBridge({
  component: component,
  components: components.ginkoCms.migrations
})

export const listContentMigrationEntries = bridge.listContentMigrationEntries
export const applyContentMigrationEntries = bridge.applyContentMigrationEntries
