// @trellis-bridge-package: @lupinum/ginko-cms
// @trellis-bridge-version: 0.1.1
// AUTO-GENERATED by Trellis - do not edit manually
import { createRevalidationBridge } from '@lupinum/ginko-cms/bridge'
import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createRevalidationBridge({
  component: component,
  components: components.ginkoCms.revalidation
})

export const listRevalidationTargets = bridge.listRevalidationTargets
export const upsertRevalidationTarget = bridge.upsertRevalidationTarget
export const listRevalidationJobs = bridge.listRevalidationJobs
export const retryRevalidationJob = bridge.retryRevalidationJob
export const previewRetryRevalidationJobOperation = bridge.previewRetryRevalidationJobOperation
