// @trellis-bridge-package: @lupinum/ginko-cms
// @trellis-bridge-version: 0.1.2
// AUTO-GENERATED by Trellis - do not edit manually
import { createSettingsBridge } from '@lupinum/ginko-cms/bridge'
import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createSettingsBridge({
  component: component,
  components: components.ginkoCms.settings
})

export const getStudioSettings = bridge.getStudioSettings
export const getSettings = bridge.getSettings
export const updateSettings = bridge.updateSettings
