// @trellis-bridge-package: @lupinum/ginko-cms
// @trellis-bridge-version: 0.1.2
// AUTO-GENERATED by Trellis - do not edit manually
import { createSiteDataBridge } from '@lupinum/ginko-cms/bridge'
import { components } from '../_generated/api'
import { component } from './_caller'

const bridge = createSiteDataBridge({
  component: component,
  components: components.ginkoCms.siteData
})

export const listSiteData = bridge.listSiteData
export const getSiteDataBlock = bridge.getSiteDataBlock
export const createSiteDataBlock = bridge.createSiteDataBlock
export const saveSiteData = bridge.saveSiteData
export const updateSiteDataBlock = bridge.updateSiteDataBlock
export const deleteSiteDataBlock = bridge.deleteSiteDataBlock
export const previewDeleteSiteDataBlockOperation = bridge.previewDeleteSiteDataBlockOperation
