import { defineMcpResource } from '@nuxtjs/mcp-toolkit/server'

export default defineMcpResource({
  name: 'ginko-public-diagnostics-guide',
  title: 'Ginko Public Diagnostics Guide',
  description: 'Read-only context for route, sitemap, search, nav, and visibility diagnostics.',
  uri: 'app://ginko-cms/diagnostics-guide',
  handler: async (uri: URL) => ({
    contents: [
      {
        uri: uri.toString(),
        mimeType: 'text/markdown',
        text: [
          '# Ginko Public Diagnostics',
          '',
          'Use diagnostics before changing or publishing content. The same diagnostic codes are used by Studio and MCP.',
          '',
          'Studio public workflow rows are a UI over this same data: locale draft/published state, public visibility, sitemap/search/nav inclusion, translation readiness, and publish-impact preview.',
          '',
          'Important tools:',
          '',
          '- `explain-public-visibility`: explains one entry and locale across route, sitemap, search, and nav.',
          '- `preview-publish`: run-bound preview for blockers and public changes without publishing.',
          '- `get-review-status`: follows a publish review requested by the current credential.',
          '- `get-entry` and `get-collection`: inspect draft state and collection capabilities.',
          '',
          'Diagnostic codes:',
          '',
          '- `data_only_collection`: the collection is structured data and does not own public routes.',
          '- `entry_collection_mismatch`: the requested entry belongs to another collection.',
          '- `unpublished_entry`: the locale exists but is not published.',
          '- `missing_locale_route`: the locale has no public route projection.',
          '- `missing_required_localized_field`: a required localized field is missing or invalid.',
          '- `missing_parent_route`: the entry parent is not public in the same locale.',
          '- `route_collision`: multiple public routes claim the same rendered href.',
          '- `route_redirect_collision`: a route and redirect claim the same rendered href.',
          '- `redirect_collision`: multiple redirects claim the same rendered href.',
          '- `redirect_target_missing`: a redirect points at a missing public href.',
          '- `excluded_from_sitemap`: the locale is excluded from sitemap output.',
          '- `excluded_from_search`: the locale is excluded from search output.',
          '- `excluded_from_nav`: the locale is excluded from nav output.',
          '- `invalid_entry_id`: the requested entry id does not resolve to an entry.',
          '',
          'Website changes preview statuses:',
          '',
          '- `ready`: the requested locale can be published and has public-impact changes.',
          '- `blocked`: publishing would fail or create unsafe public output.',
          '- `no_changes`: the draft matches the currently published public state.',
          '- `not_publishable`: the request cannot produce route-backed public output, for example data-only content.',
          '',
          'Safe publish loop:',
          '',
          '1. Inspect collection capability and entry draft state.',
          '2. Explain public visibility for the target locale.',
          '3. Call `get-readiness-detail` and `preview-publish` with the active `agentRunId`; summarize blockers, warnings, effects, route/SEO/sitemap/search/nav changes, cache tags, and events.',
          '4. Call `request-publish-review`. A preview is stale if the draft changes after it was generated.',
          '5. Call `get-review-status` to follow the human decision.',
          '',
          'Diagnostics are read-only context. Publishing and destructive actions still require the normal CMS operation permissions and confirmation flow.',
        ].join('\n'),
      },
    ],
  }),
})
