// AUTO-GENERATED by @lupinum/ginko-cms — do not edit manually
import { defineGinkoAuth } from '@lupinum/ginko-cms/convex/auth'

import { components } from './_generated/api'
import authConfig from './auth.config'
import authSchema from './betterAuth/schema'
import { sendGinkoPasswordResetEmail } from './ginkoCms/passwordRecovery'

export const { authComponent, createAuth, createAuthOptions } = defineGinkoAuth(
  { components, authConfig, authSchema },
  {
    emailPassword: true,
    passwordRecovery: {
      sendResetPassword: async ({ user, url }) => await sendGinkoPasswordResetEmail({ user, url }),
      tokenExpiresInSeconds: 60 * 60,
    },
  },
)
